apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-kustomize
  namespace: namespace-gitops-2038
spec:
  project: default
  source:
    repoURL: 'https://github.com/praveen4g0/gitops-certification-examples.git'
    path: testTemplates
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: namespace-gitops-2038
  syncPolicy:
    automated: {}
    syncOptions:
    - PruneLast=true